### ISSUE TITLE
1.20.2   Error occurred while enabling HeadDatabase v4.17.3

### ISSUE THREAD

**Issue by Blueeyestar** [Arcaniax-Development/HeadDatabase-API#43]
**When starting HDB in 1.20.2 the console always throws an error**

MinecraftVersion: CraftBukkit version 3886-Spigot-17ca32d-f0661c3 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT)

HeadDatabase: 4.17.3

[08:37:39] [Server thread/INFO]: [HeadDatabase] Enabling HeadDatabase v4.17.3
[08:37:40] [Server thread/INFO]: [HeadDatabase] §bUsing default §3"en_US.lang" §bcreated by §6Arcaniax
[08:37:40] [Server thread/ERROR]: Error occurred while enabling HeadDatabase v4.17.3 (Is it up to date?)
java.lang.NullPointerException: Profile name must not be null
	at java.util.Objects.requireNonNull(Objects.java:259) ~[?:?]
	at com.mojang.authlib.GameProfile.<init>(GameProfile.java:31) ~[authlib-5.0.47.jar:?]
	at me.arcaniax.hdb.util.HeadUtil.create(HeadUtil.java:97) ~[?:?]
	at me.arcaniax.hdb.HeadDatabaseManager.<init>(HeadDatabaseManager.java:120) ~[?:?]
	at me.arcaniax.hdb.Main.onEnable(Main.java:55) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[spigot-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugin(CraftServer.java:548) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3886-Spigot-17ca32d-f0661c3]
	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugins(CraftServer.java:462) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3886-Spigot-17ca32d-f0661c3]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:577) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3886-Spigot-17ca32d-f0661c3]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:400) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3886-Spigot-17ca32d-f0661c3]
	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:250) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3886-Spigot-17ca32d-f0661c3]
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:954) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3886-Spigot-17ca32d-f0661c3]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:298) ~[spigot-1.20.2-R0.1-SNAPSHOT.jar:3886-Spigot-17ca32d-f0661c3]
	at java.lang.Thread.run(Thread.java:1623) ~[?:?]

**Comment by NotMyFault** [comment]
This issue tracker is for the API of HDB, for HDB directly, use the support discord.
