### ISSUE TITLE
Issue with new 4.18.1

### ISSUE THREAD

**Issue by CloudeLecaw** [Arcaniax-Development/HeadDatabase-API#45]
```
[23:18:54] [Server thread/ERROR]: Could not pass event PlayerPickupItemEvent to HeadDatabase v4.18.1
java.lang.NullPointerException: Cannot invoke "String.equalsIgnoreCase(String)" because the return value of "org.bukkit.inventory.meta.SkullMeta.getOwner()" is null
	at me.arcaniax.hdb.listener.ItemPickupListener.onItemPickup(ItemPickupListener.java:36) ~[HeadDatabase_4.18.1.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor744.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:git-Paper-223]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.2.jar:git-Paper-223]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.2.jar:git-Paper-223]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.world.entity.item.ItemEntity.playerTouch(ItemEntity.java:468) ~[?:?]
	at net.minecraft.world.entity.player.Player.touch(Player.java:638) ~[?:?]
	at net.minecraft.world.entity.player.Player.aiStep(Player.java:603) ~[?:?]
	at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:3041) ~[?:?]
	at net.minecraft.world.entity.player.Player.tick(Player.java:277) ~[?:?]
	at net.minecraft.server.level.ServerPlayer.doTick(ServerPlayer.java:763) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.tick(ServerGamePacketListenerImpl.java:337) ~[?:?]
	at net.minecraft.network.Connection.tick(Connection.java:592) ~[?:?]
	at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:240) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1578) ~[paper-1.20.2.jar:git-Paper-223]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.20.2.jar:git-Paper-223]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1379) ~[paper-1.20.2.jar:git-Paper-223]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1156) ~[paper-1.20.2.jar:git-Paper-223]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-223]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
```
We have a plugin called CMI that we allow to drop mobheads with a chance of x%
When the head drops HDB throws this error in console.

**Comment by andrewkm** [comment]
This is the Github page for the API not the plugin.
Report your issues in the correct place: https://www.spigotmc.org/threads/head-database-paid.101767/

**Comment by CloudeLecaw** [comment]
hmmm did i forgot to close this? may bad.
was the only github link offered by the spigot page :3
